# Generated by Django 4.1.1 on 2023-08-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vegetation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.TextField(blank=True, null=True)),
                ('leaftype', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
