# Generated by Django 4.1.1 on 2023-08-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlayers', '0003_delete_psa scheda monitoraggio_vegetation_crownpic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSA Scheda Monitoraggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_Cella', models.TextField(blank=True, null=True)),
                ('Data_rilievo', models.DateField(blank=True, null=True)),
                ('Ora_Inizio_rilievo', models.TimeField(blank=True, null=True)),
                ('Numero_operatori_coinvolti', models.TextField(blank=True, null=True)),
                ('Numero_carcasse_rinvenute', models.TextField(blank=True, null=True)),
                ('Tracce_di_animali', models.TextField(blank=True, null=True)),
                ('Feci_di_animali', models.TextField(blank=True, null=True)),
                ('Avvistamenti_animali_giovani', models.TextField(blank=True, null=True)),
                ('Avvistamenti_maschi_adulti', models.TextField(blank=True, null=True)),
                ('Avvistamenti_femmine_adulte', models.TextField(blank=True, null=True)),
                ('Avvistamenti_indeterminati', models.TextField(blank=True, null=True)),
                ('Ora_fine_rilievo', models.TimeField(blank=True, null=True)),
                ('Note', models.TextField(blank=True, null=True)),
                ('Responsabile', models.TextField(blank=True, null=True)),
                ('Nome_e_recapito_di_compila', models.TextField(blank=True, null=True)),
                ('Firma', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
