# Generated by Django 4.2.7 on 2023-11-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlayers', '0004_psa scheda monitoraggio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PSA Scheda Monitoraggio',
        ),
        migrations.DeleteModel(
            name='vegetation',
        ),
    ]
