# Generated by Django 4.1.1 on 2023-08-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('definition', models.JSONField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.BinaryField(default=()),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='data',
            field=models.BinaryField(default=()),
        ),
        migrations.AddField(
            model_name='project',
            name='forms',
            field=models.ManyToManyField(blank=True, to='data.form'),
        ),
    ]
