# Generated by Django 4.1.1 on 2023-08-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_form_alter_image_thumbnail_alter_imagedata_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.BinaryField(default=()),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='data',
            field=models.BinaryField(default=()),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['name'], name='data_form_name_ef07ba_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['enabled'], name='data_form_enabled_2a5e66_idx'),
        ),
    ]
