# Generated by Django 4.1.1 on 2023-11-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_image_thumbnail_alter_imagedata_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.BinaryField(default=()),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='data',
            field=models.BinaryField(default=()),
        ),
    ]
