# Generated by Django 4.2.7 on 2023-11-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_image_thumbnail_alter_imagedata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='geometrytype',
            field=models.CharField(choices=[('Point', 'Point'), ('LineString', 'LineString'), ('Polygon', 'Polygon')], default='Point', max_length=10),
        ),
    ]
