# Generated by Django 4.2.7 on 2023-12-05 10:20

import data.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_rename_addtimestamp_form_add_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='show_in_projectdata',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='definition',
            field=models.JSONField(default=list, validators=[data.models.validateFormContent]),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters with no spaces are allowed.', regex='^[a-zA-Z0-9_]+$')]),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['show_in_projectdata'], name='data_form_show_in_ded7a2_idx'),
        ),
    ]
