# Generated by Django 4.0.4 on 2022-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ts', models.DateTimeField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('altim', models.FloatField()),
                ('form', models.JSONField()),
                ('marker', models.CharField(max_length=50)),
                ('size', models.FloatField()),
                ('rotation', models.FloatField()),
                ('color', models.CharField(max_length=9)),
                ('accuracy', models.FloatField()),
                ('heading', models.FloatField()),
                ('speed', models.FloatField()),
                ('speedaccuracy', models.FloatField()),
            ],
        ),
    ]
