# Generated by Django 4.1.1 on 2022-09-21 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='notesid',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.note'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.BinaryField(default=()),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='data',
            field=models.BinaryField(default=()),
        ),
        migrations.AlterField(
            model_name='note',
            name='form',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='rotation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
