/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hydrologis.gssmobile.database;

import com.codename1.db.Cursor;
import com.codename1.db.Database;
import com.codename1.db.Row;
import com.codename1.io.Util;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author hydrologis
 */
public class DaoImages {

    /**
     * Image table name.
     */
    public static final String TABLE_IMAGES = "images";

    public static List<GssImage> getImagesList(Database db) throws Exception {

        String query = "SELECT "
                + //
                ImageTableFields.COLUMN_ID.getFieldName() + ", "
                + //
                ImageTableFields.COLUMN_LON.getFieldName() + ", "
                + //
                ImageTableFields.COLUMN_LAT.getFieldName() + ", "
                + //
                ImageTableFields.COLUMN_ALTIM.getFieldName() + ", "
                + //
                ImageTableFields.COLUMN_TS.getFieldName() + ", "
                + //
                ImageTableFields.COLUMN_AZIM.getFieldName() + ", "
                + //
                ImageTableFields.COLUMN_TEXT.getFieldName() + ", "
                + //
                ImageTableFields.COLUMN_NOTE_ID.getFieldName() + ", "
                + //
                ImageTableFields.COLUMN_IMAGEDATA_ID.getFieldName() + ", "
                + //
                ImageTableFields.COLUMN_ISDIRTY.getFieldName()
                + " FROM " + TABLE_IMAGES + " where " + ImageTableFields.COLUMN_ISDIRTY.getFieldName() + "=" + 1 + " order by " + ImageTableFields.COLUMN_TS.getFieldName();

        List<GssImage> notes = new ArrayList<>();
        Cursor cursor = null;
        try {
            cursor = db.executeQuery(query);
            while (cursor.next()) {
                Row row = cursor.getRow();
                int i = 0;
                GssImage image = new GssImage();
                image.id.set(row.getLong(i++));
                image.longitude.set(row.getDouble(i++));
                image.latitude.set(row.getDouble(i++));
                image.altitude.set(row.getDouble(i++));
                image.timeStamp.set(row.getLong(i++));
                image.azimuth.set(row.getDouble(i++));
                image.text.set(row.getString(i++));
                image.noteId.set(row.getLong(i++));
                image.imageDataId.set(row.getLong(i++));
                image.isDirty.set(row.getInteger(i++));
                notes.add(image);
            }
        } finally {
            Util.cleanup(cursor);
        }
        return notes;
    }

    public static enum ImageTableFields {
        /**
         * id of the note, Generated by the db.
         */
        COLUMN_ID("_id", Long.class),
        /**
         * Longitude of the note in WGS84.
         */
        COLUMN_LON("lon", Double.class),
        /**
         * Latitude of the note in WGS84.
         */
        COLUMN_LAT("lat", Double.class),
        /**
         * Elevation of the note.
         */
        COLUMN_ALTIM("altim", Double.class),
        /**
         * Timestamp of the note.
         */
        COLUMN_TS("ts", Long.class),
        /**
         * The azimuth of the picture.
         */
        COLUMN_AZIM("azim", Double.class),
        /**
         * A name or text for the image.
         */
        COLUMN_TEXT("text", String.class),
        /**
         * Is dirty field (0=false, 1=true)
         */
        COLUMN_ISDIRTY("isdirty", Integer.class),
        /**
         * An optional note id, to which it is bound to.
         */
        COLUMN_NOTE_ID("note_id", Long.class),
        /**
         * The id of the connected image data.
         */
        COLUMN_IMAGEDATA_ID("imagedata_id", Long.class);

        private String fieldName;
        private Class fieldClass;

        ImageTableFields(String fieldName, Class fieldClass) {
            this.fieldName = fieldName;
            this.fieldClass = fieldClass;
        }

        public String getFieldName() {
            return fieldName;
        }

        public Class getFieldClass() {
            return fieldClass;
        }
    }

    public static enum ImageDataTableFields {
        /**
         * id of the note, Generated by the db.
         */
        COLUMN_ID("_id", Long.class),
        /**
         * The image data.
         */
        COLUMN_IMAGE("data", byte[].class),
        /**
         * The image thumbnail data.
         */
        COLUMN_THUMBNAIL("thumbnail", byte[].class);

        private String fieldName;
        private Class fieldClass;

        ImageDataTableFields(String fieldName, Class fieldClass) {
            this.fieldName = fieldName;
            this.fieldClass = fieldClass;
        }

        public String getFieldName() {
            return fieldName;
        }

        public Class getFieldClass() {
            return fieldClass;
        }
    }
}
